import { Router } from "express";
import { StudentController } from "../controllers";
import { uploadPhoto } from "../middlewares/upload";
const r = Router(); const c = new StudentController();
r.get("/", (req, res) => c.list(req, res));
r.get("/faces/all", (req, res) => c.getFaceDescriptors(req, res));
r.get("/:id", (req, res) => c.getById(req, res));
r.post("/", (req, res) => c.create(req, res));
r.put("/:id", (req, res) => c.update(req, res));
r.delete("/:id", (req, res) => c.delete(req, res));
r.post("/:id/photo", uploadPhoto.single("photo"), (req, res) => c.uploadPhoto(req, res));
r.get("/:id/qrcode", (req, res) => c.getQRCode(req, res));
r.post("/:id/face", (req, res) => c.updateFaceDescriptor(req, res));
export default r;